name: Minishell Ubuntu compile check CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make re
      run: |
            make re
    - name: Execute minishell
      run: ./minishell
    - name: Echo hoi
      run: echo hoi
    - name: Exit shell
      run: exit
